### ISSUE TITLE
vrms-gentoo is confused about the license of dev-util/mingw64-toolchain-10.0.0-r1

### ISSUE THREAD

**Issue by l29ah** [z411/vrms-gentoo#5]
it says `dev-util/mingw64-toolchain-10.0.0-r1 (LG)`
`cat /var/db/pkg/dev-util/mingw64-toolchain-10.0.0-r1/LICENSE` says `GPL-3+ LGPL-3+ || ( GPL-3+ libgcc libstdc++ gcc-runtime-library-exception-3.1 ) ZPL BSD BSD-2 ISC LGPL-2+ LGPL-2.1+ MIT public-domain`

**Comment by z411** [comment]
Thank you for your report!
